### ISSUE TITLE
Helper script to ease the process of adding new bugs

### ISSUE THREAD

**Issue by StefanosChaliasos** [zksecurity/zkbugs#1]
Adding an extra script that will request from the user to provide some details about the bug and then will produce a template would be useful. A nice example of such script is `add_new_entry` from [here](https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/CONTRIBUTING.md)

**Comment by ret2basic** [comment]
Solved in https://github.com/zksecurity/zkbugs/pull/31
