### ISSUE TITLE
Add tag to annotate almost identical bugs

### ISSUE THREAD

**Issue by StefanosChaliasos** [zksecurity/zkbugs#20]
Create a new field in the config file to annotate which bugs are pretty similar and have the exact same root cause in very similar code bases. E.g., bugs `iden3/circomlib/veridise-V-CIRCOMLIB-VUL-00*` are pretty similar to each other.

**Comment by ret2basic** [comment]
Solved by this PR: https://github.com/zksecurity/zkbugs/pull/34
